# Copy this into Streamlit Cloud → Settings → Secrets
# For LOCAL development, you may save this as .streamlit/secrets.toml (do NOT commit real credentials)
DATABASE_URL = "postgresql+psycopg://appuser:dheeraj%401@localhost:5432/collateral"
